@echo off

set "LATEX_USR_DATA=%HOME_DIR%\Usr\Data\latex"
set "LATEX_PKG_PDF=%LATEX_USR_DATA%\package-pdf"
set "LATEX_SRC=%HOME_DIR%\Usr\Source\latex"
set "LATEX_DL=%HOME_DIR%\Usr\Download\latex"

del "%LATEX_USR_DATA%\LongTeX1.pdf"
del "%LATEX_USR_DATA%\latexsheet-a4.pdf"
mklink /H "%LATEX_USR_DATA%\LongTeX1.pdf" "%LATEX_DL%\LongTeX1.pdf"
mklink /H "%LATEX_USR_DATA%\latexsheet-a4.pdf" "%LATEX_DL%\latexsheet-a4.pdf"

rmdir /S /Q "%LATEX_PKG_PDF%"
mkdir "%LATEX_PKG_PDF%"
mklink /H "%LATEX_PKG_PDF%\adjustbox.pdf" "%LATEX_SRC%\adjustbox\adjustbox.pdf"
mklink /H "%LATEX_PKG_PDF%\arguelles.pdf" "%LATEX_SRC%\arguelles\demo\demo-arguelles.pdf"
mklink /H "%LATEX_PKG_PDF%\blowup.pdf" "%LATEX_SRC%\blowup\blowup.pdf"
mklink /H "%LATEX_PKG_PDF%\ccicons.pdf" "%LATEX_SRC%\ccicons\ccicons.pdf"
mklink /H "%LATEX_PKG_PDF%\colorblind.pdf" "%LATEX_SRC%\colorblind\colorblind_doc.pdf"
mklink /H "%LATEX_PKG_PDF%\dnd-5e-latex-template.pdf" "%LATEX_SRC%\DND-5e-LaTeX-Template\example.pdf"
mklink /H "%LATEX_PKG_PDF%\enumext.pdf" "%LATEX_SRC%\enumext\enumext.pdf"
mklink /H "%LATEX_PKG_PDF%\fmitex-parnotes.pdf" "%LATEX_SRC%\fmitex-parnotes\parnotes.pdf"
mklink /H "%LATEX_PKG_PDF%\fontawesome.pdf" "%LATEX_SRC%\fontawesome\fontawesome6\doc\fontawesome6.pdf"
mklink /H "%LATEX_PKG_PDF%\fontawesome-latex.pdf" "%LATEX_SRC%\fontawesome-latex\templates\fontawesome.pdf"
mklink /H "%LATEX_PKG_PDF%\geometry.pdf" "%LATEX_SRC%\geometry\geometry.pdf"
mklink /H "%LATEX_PKG_PDF%\gitinfo2.pdf" "%LATEX_SRC%\gitinfo2\gitinfo2.pdf"
mklink /H "%LATEX_PKG_PDF%\gitlog.pdf" "%LATEX_SRC%\gitlog\gitlog.pdf"
mklink /H "%LATEX_PKG_PDF%\graphicxpsd.pdf" "%LATEX_SRC%\graphicxpsd\graphicxpsd.pdf"
mklink /H "%LATEX_PKG_PDF%\hackthefootline.pdf" "%LATEX_SRC%\hackthefootline\hackthefootline\doc\hackthefootline-doc.pdf"
mklink /H "%LATEX_PKG_PDF%\href-ul.pdf" "%LATEX_SRC%\href-ul\href-ul.pdf"
mklink /H "%LATEX_PKG_PDF%\hsrmbeamertheme.pdf" "%LATEX_SRC%\hsrmbeamertheme\hsrm-beamer-demo.pdf"
mklink /H "%LATEX_PKG_PDF%\invoice2.pdf" "%LATEX_SRC%\invoice2\invoice2.pdf"
mklink /H "%LATEX_PKG_PDF%\kdpcover.pdf" "%LATEX_SRC%\kdpcover\kdpcover.pdf"
mklink /H "%LATEX_PKG_PDF%\kmbeamer.pdf" "%LATEX_SRC%\kmbeamer\examples\example_Blackboard.pdf"
mklink /H "%LATEX_PKG_PDF%\latex-pagelayout.pdf" "%LATEX_SRC%\latex-pagelayout\doc\pagelayout-manual.pdf"
mklink /H "%LATEX_PKG_PDF%\latex-presentation.pdf" "%LATEX_SRC%\latex-presentation\presentation.pdf"
mklink /H "%LATEX_PKG_PDF%\latexindent.pl.pdf" "%LATEX_SRC%\latexindent.pl\documentation\latexindent.pdf"
mklink /H "%LATEX_PKG_PDF%\ltx_clrstrip.pdf" "%LATEX_SRC%\ltx_clrstrip\clrstrip.pdf"
mklink /H "%LATEX_PKG_PDF%\magicwatermark.pdf" "%LATEX_SRC%\magicwatermark\doc\magicwatermark-en.pdf"
mklink /H "%LATEX_PKG_PDF%\make4ht.pdf" "%LATEX_SRC%\make4ht\make4ht-doc.pdf"
mklink /H "%LATEX_PKG_PDF%\menukeys.pdf" "%LATEX_SRC%\menukeys\menukeys.pdf"
mklink /H "%LATEX_PKG_PDF%\mercatormap.pdf" "%LATEX_SRC%\mercatormap\doc\latex\mercatormap\mercatormap.pdf"
mklink /H "%LATEX_PKG_PDF%\microtype.pdf" "%LATEX_SRC%\microtype\microtype.pdf"
mklink /H "%LATEX_PKG_PDF%\multicolrule.pdf" "%LATEX_SRC%\multicolrule\multicolrule.pdf"
mklink /H "%LATEX_PKG_PDF%\oplotsymbl-latex.pdf" "%LATEX_SRC%\oPlotSymbl-LaTeX\oPlotSymbl-Manual-en.pdf"
mklink /H "%LATEX_PKG_PDF%\pdfprivacy.pdf" "%LATEX_SRC%\pdfprivacy\pdfprivacy.pdf"
mklink /H "%LATEX_PKG_PDF%\phfqitltx.pdf" "%LATEX_SRC%\phfqitltx\phfqit\phfqit.pdf"
mklink /H "%LATEX_PKG_PDF%\polyglossia.pdf" "%LATEX_SRC%\polyglossia\doc\polyglossia.pdf"
mklink /H "%LATEX_PKG_PDF%\q-and-a.pdf" "%LATEX_SRC%\Q-and-A\doc\Q-and-A-doc.pdf"
mklink /H "%LATEX_PKG_PDF%\quiver.pdf" "%LATEX_SRC%\quiver\package\quiver-package-documentation.pdf"
mklink /H "%LATEX_PKG_PDF%\rerunfilecheck.pdf" "%LATEX_SRC%\rerunfilecheck\rerunfilecheck.pdf"
mklink /H "%LATEX_PKG_PDF%\responsive-latex.pdf" "%LATEX_SRC%\responsive-latex\responsive-doc.pdf"
mklink /H "%LATEX_PKG_PDF%\sectionbreak.pdf" "%LATEX_SRC%\sectionbreak\sectionbreak-doc.pdf"
mklink /H "%LATEX_PKG_PDF%\semesterplanner.pdf" "%LATEX_SRC%\semesterplanner\docs.pdf"
mklink /H "%LATEX_PKG_PDF%\semesterplannerlua.pdf" "%LATEX_SRC%\semesterplannerLua\semesterplannerlua.pdf"
mklink /H "%LATEX_PKG_PDF%\sidenotesplus.pdf" "%LATEX_SRC%\sidenotesplus\sidenotesplus.pdf"
mklink /H "%LATEX_PKG_PDF%\skrapport.pdf" "%LATEX_SRC%\skrapport\skrapport.pdf"
mklink /H "%LATEX_PKG_PDF%\soulpos.pdf" "%LATEX_SRC%\soulpos\soulpos.pdf"
mklink /H "%LATEX_PKG_PDF%\stage.pdf" "%LATEX_SRC%\stage\stage-documentation.pdf"
mklink /H "%LATEX_PKG_PDF%\tabularray.pdf" "%LATEX_SRC%\tabularray\manual\manual.pdf"
mklink /H "%LATEX_PKG_PDF%\tex4ebook.pdf" "%LATEX_SRC%\tex4ebook\tex4ebook-doc.pdf"
mklink /H "%LATEX_PKG_PDF%\tikzducks.pdf" "%LATEX_SRC%\tikzducks\DOCUMENTATION.pdf"
mklink /H "%LATEX_PKG_PDF%\truchet.pdf" "%LATEX_SRC%\truchet\tikz-truchet.pdf"
mklink /H "%LATEX_PKG_PDF%\typed-checklist.pdf" "%LATEX_SRC%\typed-checklist\typed-checklist.pdf"
mklink /H "%LATEX_PKG_PDF%\typog.pdf" "%LATEX_SRC%\typog\docs\typog.pdf"
mklink /H "%LATEX_PKG_PDF%\unifront.pdf" "%LATEX_SRC%\unifront\unifront-manual.pdf"
mklink /H "%LATEX_PKG_PDF%\wallcalendar.pdf" "%LATEX_SRC%\wallcalendar\wallcalendar.pdf"

:: Later
mklink /H "%LATEX_PKG_PDF%\array.pdf" "%LATEX_DL%\tools\array.pdf"
mklink /H "%LATEX_PKG_PDF%\fbb.pdf" "%LATEX_DL%\fbb\doc\fbb-doc.pdf"

:: Others
rem "geneve_1564\geneve_1564.pdf"
rem "thesis-invitation\sample_output.pdf"

pause