@echo off

setlocal

echo "Set environment variables"
echo "---"
set "GOLDENDICT_DATA=%SCOOP_APPS_DIR%\goldendict\current\portable"
set "GOLDENDICT_DIR=%SCOOP_APPS_DIR%\goldendict\current"
set "GOLDENDICT_DOTFILE=%HOME_DIR%\Git\dotfiles\goldendict"
set "GOLDENDICT_SRC=%HOME_DIR%\Usr\Source\goldendict"
set "GOLDENDICT_DL=%HOME_DIR%\Usr\Download\goldendict"
echo(

echo Setup GoldenDict config
echo ---
rmdir /S /Q "%GOLDENDICT_DIR%\extras"
rmdir /S /Q "%GOLDENDICT_DIR%\icons"
rmdir /S /Q "%GOLDENDICT_DATA%\fonts"
rmdir /S /Q "%GOLDENDICT_DATA%\styles"
mklink /J "%GOLDENDICT_DIR%\extras" "%GOLDENDICT_SRC%\GoldenDict-Full-Dark-Theme\GoldenDict\extras"
mklink /J "%GOLDENDICT_DIR%\icons" "%GOLDENDICT_SRC%\GoldenDict-Full-Dark-Theme\GoldenDict\icons"
mklink /J "%GOLDENDICT_DATA%\fonts" "%GOLDENDICT_SRC%\GoldenDict-Full-Dark-Theme\GoldenDict\fonts"
mkdir "%GOLDENDICT_DATA%\styles\Dark"
type "%GOLDENDICT_SRC%\GoldenDict-Full-Dark-Theme\GoldenDict\styles\Dark\article-style.css" "%GOLDENDICT_DOTFILE%\article-style_user.css" > "%GOLDENDICT_DATA%\styles\Dark\article-style.css"
mklink "%GOLDENDICT_DATA%\styles\Dark\qt-style.css" "%GOLDENDICT_SRC%\GoldenDict-Full-Dark-Theme\GoldenDict\styles\Dark\qt-style.css"
copy "%GOLDENDICT_DOTFILE%\config" "%GOLDENDICT_DOTFILE%\config.linkfile"
mklink "%GOLDENDICT_DATA%\config" "%GOLDENDICT_DOTFILE%\config.linkfile"
:: Add config.linkfile into .gitignore
rmdir /S /Q "%GOLDENDICT_DIR%\content"
mkdir "%GOLDENDICT_DIR%\content"
mklink /J "%GOLDENDICT_DIR%\content\files_mdx" "%GOLDENDICT_DL%\files_mdx"
mklink /J "%GOLDENDICT_DIR%\content\files_stardict" "%GOLDENDICT_DL%\files_stardict"
mklink /J "%GOLDENDICT_DIR%\content\files_zim" "%GOLDENDICT_DL%\files_zim"
mklink /J "%GOLDENDICT_DIR%\content\morphology" "%GOLDENDICT_DL%\morphology"
mkdir "%GOLDENDICT_DIR%\content\sound-dirs"
mklink /J "%GOLDENDICT_DIR%\content\sound-dirs\Forvo_pron" "%GOLDENDICT_DL%\sound-dirs\Forvo_pron"
mklink "%GOLDENDICT_DIR%\content\sound-dirs\pronunciations-en.zips" "%GOLDENDICT_DL%\sound-dirs\pronunciations-en.zips"
mklink "%GOLDENDICT_DIR%\content\sound-dirs\kokoro-tts_etymonline.zips" "%GOLDENDICT_DL%\sound-dirs\kokoro-tts_etymonline.zips"
echo(

echo Setup Forvo_pron
echo ---
set "FORVO_PRON=%GOLDENDICT_DL%\sound-dirs\Forvo_pron"
set "FORVO_OPUS=%GOLDENDICT_DL%\sound-dirs\Forvo_pronunciations\export\opus"
set "FORVO_DSL=%GOLDENDICT_DL%\sound-dirs\ForvoDSL\ForvoDSL-20220513"
rmdir /S /Q "%FORVO_PRON%"
mkdir "%FORVO_PRON%"
mklink "%FORVO_PRON%\ForvoAfrikaans.dsl" "%FORVO_DSL%\ForvoAfrikaans.dsl"
mklink "%FORVO_PRON%\ForvoAlbanian.dsl" "%FORVO_DSL%\ForvoAlbanian.dsl"
mklink "%FORVO_PRON%\ForvoAncientGreek.dsl" "%FORVO_DSL%\ForvoAncientGreek.dsl"
mklink "%FORVO_PRON%\ForvoArabic.dsl" "%FORVO_DSL%\ForvoArabic.dsl"
mklink "%FORVO_PRON%\ForvoArmenian.dsl" "%FORVO_DSL%\ForvoArmenian.dsl"
mklink "%FORVO_PRON%\ForvoAzerbaijani.dsl" "%FORVO_DSL%\ForvoAzerbaijani.dsl"
mklink "%FORVO_PRON%\ForvoBasque.dsl" "%FORVO_DSL%\ForvoBasque.dsl"
mklink "%FORVO_PRON%\ForvoBelarusian.dsl" "%FORVO_DSL%\ForvoBelarusian.dsl"
mklink "%FORVO_PRON%\ForvoBengali.dsl" "%FORVO_DSL%\ForvoBengali.dsl"
mklink "%FORVO_PRON%\ForvoBreton.dsl" "%FORVO_DSL%\ForvoBreton.dsl"
mklink "%FORVO_PRON%\ForvoBulgarian.dsl" "%FORVO_DSL%\ForvoBulgarian.dsl"
mklink "%FORVO_PRON%\ForvoCantonese.dsl" "%FORVO_DSL%\ForvoCantonese.dsl"
mklink "%FORVO_PRON%\ForvoCatalan.dsl" "%FORVO_DSL%\ForvoCatalan.dsl"
mklink "%FORVO_PRON%\ForvoCroatian.dsl" "%FORVO_DSL%\ForvoCroatian.dsl"
mklink "%FORVO_PRON%\ForvoCzech.dsl" "%FORVO_DSL%\ForvoCzech.dsl"
mklink "%FORVO_PRON%\ForvoDanish.dsl" "%FORVO_DSL%\ForvoDanish.dsl"
mklink "%FORVO_PRON%\ForvoDutch.dsl" "%FORVO_DSL%\ForvoDutch.dsl"
mklink "%FORVO_PRON%\ForvoEnglish.dsl" "%FORVO_DSL%\ForvoEnglish.dsl"
mklink "%FORVO_PRON%\ForvoEsperanto.dsl" "%FORVO_DSL%\ForvoEsperanto.dsl"
mklink "%FORVO_PRON%\ForvoEstonian.dsl" "%FORVO_DSL%\ForvoEstonian.dsl"
mklink "%FORVO_PRON%\ForvoFinnish.dsl" "%FORVO_DSL%\ForvoFinnish.dsl"
mklink "%FORVO_PRON%\ForvoFrench.dsl" "%FORVO_DSL%\ForvoFrench.dsl"
mklink "%FORVO_PRON%\ForvoFrisian.dsl" "%FORVO_DSL%\ForvoFrisian.dsl"
mklink "%FORVO_PRON%\ForvoGan.dsl" "%FORVO_DSL%\ForvoGan.dsl"
mklink "%FORVO_PRON%\ForvoGeorgian.dsl" "%FORVO_DSL%\ForvoGeorgian.dsl"
mklink "%FORVO_PRON%\ForvoGerman.dsl" "%FORVO_DSL%\ForvoGerman.dsl"
mklink "%FORVO_PRON%\ForvoGreek.dsl" "%FORVO_DSL%\ForvoGreek.dsl"
mklink "%FORVO_PRON%\ForvoHakka.dsl" "%FORVO_DSL%\ForvoHakka.dsl"
mklink "%FORVO_PRON%\ForvoHebrew.dsl" "%FORVO_DSL%\ForvoHebrew.dsl"
mklink "%FORVO_PRON%\ForvoHindi.dsl" "%FORVO_DSL%\ForvoHindi.dsl"
mklink "%FORVO_PRON%\ForvoHungarian.dsl" "%FORVO_DSL%\ForvoHungarian.dsl"
mklink "%FORVO_PRON%\ForvoIcelandic.dsl" "%FORVO_DSL%\ForvoIcelandic.dsl"
mklink "%FORVO_PRON%\ForvoIndonesian.dsl" "%FORVO_DSL%\ForvoIndonesian.dsl"
mklink "%FORVO_PRON%\ForvoIrish.dsl" "%FORVO_DSL%\ForvoIrish.dsl"
mklink "%FORVO_PRON%\ForvoItalian.dsl" "%FORVO_DSL%\ForvoItalian.dsl"
mklink "%FORVO_PRON%\ForvoJapanese.dsl" "%FORVO_DSL%\ForvoJapanese.dsl"
mklink "%FORVO_PRON%\ForvoJin.dsl" "%FORVO_DSL%\ForvoJin.dsl"
mklink "%FORVO_PRON%\ForvoKazakh.dsl" "%FORVO_DSL%\ForvoKazakh.dsl"
mklink "%FORVO_PRON%\ForvoKorean.dsl" "%FORVO_DSL%\ForvoKorean.dsl"
mklink "%FORVO_PRON%\ForvoLatin.dsl" "%FORVO_DSL%\ForvoLatin.dsl"
mklink "%FORVO_PRON%\ForvoLatvian.dsl" "%FORVO_DSL%\ForvoLatvian.dsl"
mklink "%FORVO_PRON%\ForvoLithuanian.dsl" "%FORVO_DSL%\ForvoLithuanian.dsl"
mklink "%FORVO_PRON%\ForvoLuxembourgish.dsl" "%FORVO_DSL%\ForvoLuxembourgish.dsl"
mklink "%FORVO_PRON%\ForvoMalay.dsl" "%FORVO_DSL%\ForvoMalay.dsl"
mklink "%FORVO_PRON%\ForvoMandarin.dsl" "%FORVO_DSL%\ForvoMandarin.dsl"
mklink "%FORVO_PRON%\ForvoMinDong.dsl" "%FORVO_DSL%\ForvoMinDong.dsl"
mklink "%FORVO_PRON%\ForvoMinNan.dsl" "%FORVO_DSL%\ForvoMinNan.dsl"
mklink "%FORVO_PRON%\ForvoMongolian.dsl" "%FORVO_DSL%\ForvoMongolian.dsl"
mklink "%FORVO_PRON%\ForvoNahuatl.dsl" "%FORVO_DSL%\ForvoNahuatl.dsl"
mklink "%FORVO_PRON%\ForvoNorwegian.dsl" "%FORVO_DSL%\ForvoNorwegian.dsl"
mklink "%FORVO_PRON%\ForvoPersian.dsl" "%FORVO_DSL%\ForvoPersian.dsl"
mklink "%FORVO_PRON%\ForvoPolish.dsl" "%FORVO_DSL%\ForvoPolish.dsl"
mklink "%FORVO_PRON%\ForvoPortuguese.dsl" "%FORVO_DSL%\ForvoPortuguese.dsl"
mklink "%FORVO_PRON%\ForvoPunjabi.dsl" "%FORVO_DSL%\ForvoPunjabi.dsl"
mklink "%FORVO_PRON%\ForvoRomanian.dsl" "%FORVO_DSL%\ForvoRomanian.dsl"
mklink "%FORVO_PRON%\ForvoRussian.dsl" "%FORVO_DSL%\ForvoRussian.dsl"
mklink "%FORVO_PRON%\ForvoSanskrit.dsl" "%FORVO_DSL%\ForvoSanskrit.dsl"
mklink "%FORVO_PRON%\ForvoScots.dsl" "%FORVO_DSL%\ForvoScots.dsl"
mklink "%FORVO_PRON%\ForvoScottishGaelic.dsl" "%FORVO_DSL%\ForvoScottishGaelic.dsl"
mklink "%FORVO_PRON%\ForvoSerbian.dsl" "%FORVO_DSL%\ForvoSerbian.dsl"
mklink "%FORVO_PRON%\ForvoSlovak.dsl" "%FORVO_DSL%\ForvoSlovak.dsl"
mklink "%FORVO_PRON%\ForvoSlovenian.dsl" "%FORVO_DSL%\ForvoSlovenian.dsl"
mklink "%FORVO_PRON%\ForvoSouthwesternMandarin.dsl" "%FORVO_DSL%\ForvoSouthwesternMandarin.dsl"
mklink "%FORVO_PRON%\ForvoSpanish.dsl" "%FORVO_DSL%\ForvoSpanish.dsl"
mklink "%FORVO_PRON%\ForvoSwahili.dsl" "%FORVO_DSL%\ForvoSwahili.dsl"
mklink "%FORVO_PRON%\ForvoSwedish.dsl" "%FORVO_DSL%\ForvoSwedish.dsl"
mklink "%FORVO_PRON%\ForvoTagalog.dsl" "%FORVO_DSL%\ForvoTagalog.dsl"
mklink "%FORVO_PRON%\ForvoTamil.dsl" "%FORVO_DSL%\ForvoTamil.dsl"
mklink "%FORVO_PRON%\ForvoTatar.dsl" "%FORVO_DSL%\ForvoTatar.dsl"
mklink "%FORVO_PRON%\ForvoThai.dsl" "%FORVO_DSL%\ForvoThai.dsl"
mklink "%FORVO_PRON%\ForvoToisaneseCantonese.dsl" "%FORVO_DSL%\ForvoToisaneseCantonese.dsl"
mklink "%FORVO_PRON%\ForvoTurkish.dsl" "%FORVO_DSL%\ForvoTurkish.dsl"
mklink "%FORVO_PRON%\ForvoUkrainian.dsl" "%FORVO_DSL%\ForvoUkrainian.dsl"
mklink "%FORVO_PRON%\ForvoUrdu.dsl" "%FORVO_DSL%\ForvoUrdu.dsl"
mklink "%FORVO_PRON%\ForvoUyghur.dsl" "%FORVO_DSL%\ForvoUyghur.dsl"
mklink "%FORVO_PRON%\ForvoUzbek.dsl" "%FORVO_DSL%\ForvoUzbek.dsl"
mklink "%FORVO_PRON%\ForvoVietnamese.dsl" "%FORVO_DSL%\ForvoVietnamese.dsl"
mklink "%FORVO_PRON%\ForvoWelsh.dsl" "%FORVO_DSL%\ForvoWelsh.dsl"
mklink "%FORVO_PRON%\ForvoWu.dsl" "%FORVO_DSL%\ForvoWu.dsl"
mklink "%FORVO_PRON%\ForvoXiang.dsl" "%FORVO_DSL%\ForvoXiang.dsl"
mklink "%FORVO_PRON%\ForvoYiddish.dsl" "%FORVO_DSL%\ForvoYiddish.dsl"
mklink "%FORVO_PRON%\ForvoZhuang.dsl" "%FORVO_DSL%\ForvoZhuang.dsl"
mklink "%FORVO_PRON%\ForvoAfrikaans.dsl.files.zip" "%FORVO_OPUS%\af.zip"
mklink "%FORVO_PRON%\ForvoAlbanian.dsl.files.zip" "%FORVO_OPUS%\sq.zip"
mklink "%FORVO_PRON%\ForvoAncientGreek.dsl.files.zip" "%FORVO_OPUS%\grc.zip"
mklink "%FORVO_PRON%\ForvoArabic.dsl.files.zip" "%FORVO_OPUS%\ar.zip"
mklink "%FORVO_PRON%\ForvoArmenian.dsl.files.zip" "%FORVO_OPUS%\hy.zip"
mklink "%FORVO_PRON%\ForvoAzerbaijani.dsl.files.zip" "%FORVO_OPUS%\az.zip"
mklink "%FORVO_PRON%\ForvoBasque.dsl.files.zip" "%FORVO_OPUS%\eu.zip"
mklink "%FORVO_PRON%\ForvoBelarusian.dsl.files.zip" "%FORVO_OPUS%\be.zip"
mklink "%FORVO_PRON%\ForvoBengali.dsl.files.zip" "%FORVO_OPUS%\bn.zip"
mklink "%FORVO_PRON%\ForvoBreton.dsl.files.zip" "%FORVO_OPUS%\br.zip"
mklink "%FORVO_PRON%\ForvoBulgarian.dsl.files.zip" "%FORVO_OPUS%\bg.zip"
mklink "%FORVO_PRON%\ForvoCantonese.dsl.files.zip" "%FORVO_OPUS%\yue.zip"
mklink "%FORVO_PRON%\ForvoCatalan.dsl.files.zip" "%FORVO_OPUS%\ca.zip"
mklink "%FORVO_PRON%\ForvoCroatian.dsl.files.zip" "%FORVO_OPUS%\hr.zip"
mklink "%FORVO_PRON%\ForvoCzech.dsl.files.zip" "%FORVO_OPUS%\cs.zip"
mklink "%FORVO_PRON%\ForvoDanish.dsl.files.zip" "%FORVO_OPUS%\da.zip"
mklink "%FORVO_PRON%\ForvoDutch.dsl.files.zip" "%FORVO_OPUS%\nl.zip"
mklink "%FORVO_PRON%\ForvoEnglish.dsl.files.zip" "%FORVO_OPUS%\en.zip"
mklink "%FORVO_PRON%\ForvoEsperanto.dsl.files.zip" "%FORVO_OPUS%\eo.zip"
mklink "%FORVO_PRON%\ForvoEstonian.dsl.files.zip" "%FORVO_OPUS%\et.zip"
mklink "%FORVO_PRON%\ForvoFinnish.dsl.files.zip" "%FORVO_OPUS%\fi.zip"
mklink "%FORVO_PRON%\ForvoFrench.dsl.files.zip" "%FORVO_OPUS%\fr.zip"
mklink "%FORVO_PRON%\ForvoFrisian.dsl.files.zip" "%FORVO_OPUS%\fy.zip"
mklink "%FORVO_PRON%\ForvoGan.dsl.files.zip" "%FORVO_OPUS%\gan.zip"
mklink "%FORVO_PRON%\ForvoGeorgian.dsl.files.zip" "%FORVO_OPUS%\ka.zip"
mklink "%FORVO_PRON%\ForvoGerman.dsl.files.zip" "%FORVO_OPUS%\de.zip"
mklink "%FORVO_PRON%\ForvoGreek.dsl.files.zip" "%FORVO_OPUS%\el.zip"
mklink "%FORVO_PRON%\ForvoHakka.dsl.files.zip" "%FORVO_OPUS%\hak.zip"
mklink "%FORVO_PRON%\ForvoHebrew.dsl.files.zip" "%FORVO_OPUS%\he.zip"
mklink "%FORVO_PRON%\ForvoHindi.dsl.files.zip" "%FORVO_OPUS%\hi.zip"
mklink "%FORVO_PRON%\ForvoHungarian.dsl.files.zip" "%FORVO_OPUS%\hu.zip"
mklink "%FORVO_PRON%\ForvoIcelandic.dsl.files.zip" "%FORVO_OPUS%\is.zip"
mklink "%FORVO_PRON%\ForvoIndonesian.dsl.files.zip" "%FORVO_OPUS%\ind.zip"
mklink "%FORVO_PRON%\ForvoIrish.dsl.files.zip" "%FORVO_OPUS%\_ga.zip"
mklink "%FORVO_PRON%\ForvoItalian.dsl.files.zip" "%FORVO_OPUS%\it.zip"
mklink "%FORVO_PRON%\ForvoJapanese.dsl.files.zip" "%FORVO_OPUS%\ja.zip"
mklink "%FORVO_PRON%\ForvoJin.dsl.files.zip" "%FORVO_OPUS%\cjy.zip"
mklink "%FORVO_PRON%\ForvoKazakh.dsl.files.zip" "%FORVO_OPUS%\kk.zip"
mklink "%FORVO_PRON%\ForvoKorean.dsl.files.zip" "%FORVO_OPUS%\ko.zip"
mklink "%FORVO_PRON%\ForvoLatin.dsl.files.zip" "%FORVO_OPUS%\la.zip"
mklink "%FORVO_PRON%\ForvoLatvian.dsl.files.zip" "%FORVO_OPUS%\lv.zip"
mklink "%FORVO_PRON%\ForvoLithuanian.dsl.files.zip" "%FORVO_OPUS%\lt.zip"
mklink "%FORVO_PRON%\ForvoLuxembourgish.dsl.files.zip" "%FORVO_OPUS%\lb.zip"
mklink "%FORVO_PRON%\ForvoMalay.dsl.files.zip" "%FORVO_OPUS%\ms.zip"
mklink "%FORVO_PRON%\ForvoMandarinChinese.dsl.files.zip" "%FORVO_OPUS%\zh.zip"
mklink "%FORVO_PRON%\ForvoMinDong.dsl.files.zip" "%FORVO_OPUS%\cdo.zip"
mklink "%FORVO_PRON%\ForvoMinNan.dsl.files.zip" "%FORVO_OPUS%\nan.zip"
mklink "%FORVO_PRON%\ForvoMongolian.dsl.files.zip" "%FORVO_OPUS%\mn.zip"
mklink "%FORVO_PRON%\ForvoNahuatl.dsl.files.zip" "%FORVO_OPUS%\nah.zip"
mklink "%FORVO_PRON%\ForvoNorwegianBokmål.dsl.files.zip" "%FORVO_OPUS%\no.zip"
mklink "%FORVO_PRON%\ForvoPersian.dsl.files.zip" "%FORVO_OPUS%\fa.zip"
mklink "%FORVO_PRON%\ForvoPolish.dsl.files.zip" "%FORVO_OPUS%\pl.zip"
mklink "%FORVO_PRON%\ForvoPortuguese.dsl.files.zip" "%FORVO_OPUS%\pt.zip"
mklink "%FORVO_PRON%\ForvoPunjabi.dsl.files.zip" "%FORVO_OPUS%\pa.zip"
mklink "%FORVO_PRON%\ForvoRomanian.dsl.files.zip" "%FORVO_OPUS%\ro.zip"
mklink "%FORVO_PRON%\ForvoRussian.dsl.files.zip" "%FORVO_OPUS%\ru.zip"
mklink "%FORVO_PRON%\ForvoSanskrit.dsl.files.zip" "%FORVO_OPUS%\sa.zip"
mklink "%FORVO_PRON%\ForvoScots.dsl.files.zip" "%FORVO_OPUS%\sco.zip"
mklink "%FORVO_PRON%\ForvoScottishGaelic.dsl.files.zip" "%FORVO_OPUS%\gd.zip"
mklink "%FORVO_PRON%\ForvoSerbian.dsl.files.zip" "%FORVO_OPUS%\sr.zip"
mklink "%FORVO_PRON%\ForvoSlovak.dsl.files.zip" "%FORVO_OPUS%\sk.zip"
mklink "%FORVO_PRON%\ForvoSlovenian.dsl.files.zip" "%FORVO_OPUS%\sl.zip"
mklink "%FORVO_PRON%\ForvoSouthwesternMandarin.dsl.files.zip" "%FORVO_OPUS%\xghu.zip"
mklink "%FORVO_PRON%\ForvoSpanish.dsl.files.zip" "%FORVO_OPUS%\es.zip"
mklink "%FORVO_PRON%\ForvoSwahili.dsl.files.zip" "%FORVO_OPUS%\sw.zip"
mklink "%FORVO_PRON%\ForvoSwedish.dsl.files.zip" "%FORVO_OPUS%\sv.zip"
mklink "%FORVO_PRON%\ForvoTagalog.dsl.files.zip" "%FORVO_OPUS%\tl.zip"
mklink "%FORVO_PRON%\ForvoTamil.dsl.files.zip" "%FORVO_OPUS%\ta.zip"
mklink "%FORVO_PRON%\ForvoTatar.dsl.files.zip" "%FORVO_OPUS%\tt.zip"
mklink "%FORVO_PRON%\ForvoThai.dsl.files.zip" "%FORVO_OPUS%\th.zip"
mklink "%FORVO_PRON%\ForvoToisaneseCantonese.dsl.files.zip" "%FORVO_OPUS%\tisa.zip"
mklink "%FORVO_PRON%\ForvoTurkish.dsl.files.zip" "%FORVO_OPUS%\tr.zip"
mklink "%FORVO_PRON%\ForvoUkrainian.dsl.files.zip" "%FORVO_OPUS%\uk.zip"
mklink "%FORVO_PRON%\ForvoUrdu.dsl.files.zip" "%FORVO_OPUS%\ur.zip"
mklink "%FORVO_PRON%\ForvoUyghur.dsl.files.zip" "%FORVO_OPUS%\ug.zip"
mklink "%FORVO_PRON%\ForvoUzbek.dsl.files.zip" "%FORVO_OPUS%\uz.zip"
mklink "%FORVO_PRON%\ForvoVietnamese.dsl.files.zip" "%FORVO_OPUS%\vi.zip"
mklink "%FORVO_PRON%\ForvoWelsh.dsl.files.zip" "%FORVO_OPUS%\cy.zip"
mklink "%FORVO_PRON%\ForvoWu.dsl.files.zip" "%FORVO_OPUS%\wuu.zip"
mklink "%FORVO_PRON%\ForvoXiang.dsl.files.zip" "%FORVO_OPUS%\hsn.zip"
mklink "%FORVO_PRON%\ForvoYiddish.dsl.files.zip" "%FORVO_OPUS%\yi.zip"
mklink "%FORVO_PRON%\ForvoZhuang.dsl.files.zip" "%FORVO_OPUS%\za.zip"
echo(

echo Setup GoldenDictOCR
echo ---
del %GOLDENDICT_SRC%\GoldenDictOCR\IncludeAHK\GdOcrTool.ahk
del %GOLDENDICT_SRC%\GoldenDictOCR\IncludeAHK\GoldenDict.ahk
mklink %GOLDENDICT_SRC%\GoldenDictOCR\IncludeAHK\GdOcrTool.ahk %GOLDENDICT_DOTFILE%\GoldenDictOCR\IncludeAHK\GdOcrTool.ahk
mklink %GOLDENDICT_SRC%\GoldenDictOCR\IncludeAHK\GoldenDict.ahk %GOLDENDICT_DOTFILE%\GoldenDictOCR\IncludeAHK\GoldenDict.ahk
echo(

endlocal

pause