#!/bin/bash

echo "Set environment variables"
echo "---"
export HOME="/home/<username>"
export GOLDENDICT_DATA="$SCOOP_APPS_DIR/goldendict/current/portable"
export GOLDENDICT_DIR="$SCOOP_APPS_DIR/goldendict/current"
export GOLDENDICT_DOTFILE="$HOME/Git/dotfiles/goldendict"
export GOLDENDICT_SRC="$HOME/Usr/Source/goldendict"
export GOLDENDICT_DL="$HOME/Usr/Download/goldendict"
echo ""

echo "Setup GoldenDict config"
echo "---"
rm -rf "$GOLDENDICT_DIR/extras"
rm -rf "$GOLDENDICT_DIR/icons"
rm -rf "$GOLDENDICT_DATA/fonts"
rm -rf "$GOLDENDICT_DATA/styles"
ln -s "$GOLDENDICT_SRC/GoldenDict-Full-Dark-Theme/GoldenDict/extras" "$GOLDENDICT_DIR/extras"
ln -s "$GOLDENDICT_SRC/GoldenDict-Full-Dark-Theme/GoldenDict/icons" "$GOLDENDICT_DIR/icons"
ln -s "$GOLDENDICT_SRC/GoldenDict-Full-Dark-Theme/GoldenDict/fonts" "$GOLDENDICT_DATA/fonts"
mkdir -p "$GOLDENDICT_DATA/styles/Dark"
cat "$GOLDENDICT_SRC/GoldenDict-Full-Dark-Theme/GoldenDict/styles/Dark/article-style.css" "$GOLDENDICT_DOTFILE/article-style_user.css" > "$GOLDENDICT_DATA/styles/Dark/article-style.css"
ln -s "$GOLDENDICT_SRC/GoldenDict-Full-Dark-Theme/GoldenDict/styles/Dark/qt-style.css" "$GOLDENDICT_DATA/styles/Dark/qt-style.css"
cp "$GOLDENDICT_DOTFILE/config" "$GOLDENDICT_DOTFILE/config.linkfile"
ln -s "$GOLDENDICT_DOTFILE/config.linkfile" "$GOLDENDICT_DATA/config"
# Add config.linkfile into .gitignore (not implemented as it's beyond the scope)
rm -rf "$GOLDENDICT_DIR/content"
mkdir -p "$GOLDENDICT_DIR/content"
ln -s "$GOLDENDICT_DL/files_mdx" "$GOLDENDICT_DIR/content/files_mdx"
ln -s "$GOLDENDICT_DL/files_stardict" "$GOLDENDICT_DIR/content/files_stardict"
ln -s "$GOLDENDICT_DL/files_zim" "$GOLDENDICT_DIR/content/files_zim"
ln -s "$GOLDENDICT_DL/morphology" "$GOLDENDICT_DIR/content/morphology"
ln -s "$GOLDENDICT_DL/sound-dirs" "$GOLDENDICT_DIR/content/sound-dirs"
echo ""

echo "Setup Forvo_pron"
echo "---"
export FORVO_PRON="$GOLDENDICT_DL/sound-dirs/Forvo_pron"
export FORVO_OPUS="$GOLDENDICT_DL/sound-dirs/Forvo_pronunciations/export/opus"
export FORVO_DSL="$GOLDENDICT_DL/sound-dirs/ForvoDSL/ForvoDSL-20220513"
if [ -d "$FORVO_PRON" ]; then
    rm -rf "$FORVO_PRON"
fi
mkdir -p "$FORVO_PRON"
ln -s "$FORVO_DSL/ForvoAfrikaans.dsl" "$FORVO_PRON/ForvoAfrikaans.dsl"
ln -s "$FORVO_DSL/ForvoAlbanian.dsl" "$FORVO_PRON/ForvoAlbanian.dsl"
ln -s "$FORVO_DSL/ForvoAncientGreek.dsl" "$FORVO_PRON/ForvoAncientGreek.dsl"
ln -s "$FORVO_DSL/ForvoArabic.dsl" "$FORVO_PRON/ForvoArabic.dsl"
ln -s "$FORVO_DSL/ForvoArmenian.dsl" "$FORVO_PRON/ForvoArmenian.dsl"
ln -s "$FORVO_DSL/ForvoAzerbaijani.dsl" "$FORVO_PRON/ForvoAzerbaijani.dsl"
ln -s "$FORVO_DSL/ForvoBasque.dsl" "$FORVO_PRON/ForvoBasque.dsl"
ln -s "$FORVO_DSL/ForvoBelarusian.dsl" "$FORVO_PRON/ForvoBelarusian.dsl"
ln -s "$FORVO_DSL/ForvoBengali.dsl" "$FORVO_PRON/ForvoBengali.dsl"
ln -s "$FORVO_DSL/ForvoBreton.dsl" "$FORVO_PRON/ForvoBreton.dsl"
ln -s "$FORVO_DSL/ForvoBulgarian.dsl" "$FORVO_PRON/ForvoBulgarian.dsl"
ln -s "$FORVO_DSL/ForvoCantonese.dsl" "$FORVO_PRON/ForvoCantonese.dsl"
ln -s "$FORVO_DSL/ForvoCatalan.dsl" "$FORVO_PRON/ForvoCatalan.dsl"
ln -s "$FORVO_DSL/ForvoCroatian.dsl" "$FORVO_PRON/ForvoCroatian.dsl"
ln -s "$FORVO_DSL/ForvoCzech.dsl" "$FORVO_PRON/ForvoCzech.dsl"
ln -s "$FORVO_DSL/ForvoDanish.dsl" "$FORVO_PRON/ForvoDanish.dsl"
ln -s "$FORVO_DSL/ForvoDutch.dsl" "$FORVO_PRON/ForvoDutch.dsl"
ln -s "$FORVO_DSL/ForvoEnglish.dsl" "$FORVO_PRON/ForvoEnglish.dsl"
ln -s "$FORVO_DSL/ForvoEsperanto.dsl" "$FORVO_PRON/ForvoEsperanto.dsl"
ln -s "$FORVO_DSL/ForvoEstonian.dsl" "$FORVO_PRON/ForvoEstonian.dsl"
ln -s "$FORVO_DSL/ForvoFinnish.dsl" "$FORVO_PRON/ForvoFinnish.dsl"
ln -s "$FORVO_DSL/ForvoFrench.dsl" "$FORVO_PRON/ForvoFrench.dsl"
ln -s "$FORVO_DSL/ForvoFrisian.dsl" "$FORVO_PRON/ForvoFrisian.dsl"
ln -s "$FORVO_DSL/ForvoGan.dsl" "$FORVO_PRON/ForvoGan.dsl"
ln -s "$FORVO_DSL/ForvoGeorgian.dsl" "$FORVO_PRON/ForvoGeorgian.dsl"
ln -s "$FORVO_DSL/ForvoGerman.dsl" "$FORVO_PRON/ForvoGerman.dsl"
ln -s "$FORVO_DSL/ForvoGreek.dsl" "$FORVO_PRON/ForvoGreek.dsl"
ln -s "$FORVO_DSL/ForvoHakka.dsl" "$FORVO_PRON/ForvoHakka.dsl"
ln -s "$FORVO_DSL/ForvoHebrew.dsl" "$FORVO_PRON/ForvoHebrew.dsl"
ln -s "$FORVO_DSL/ForvoHindi.dsl" "$FORVO_PRON/ForvoHindi.dsl"
ln -s "$FORVO_DSL/ForvoHungarian.dsl" "$FORVO_PRON/ForvoHungarian.dsl"
ln -s "$FORVO_DSL/ForvoIcelandic.dsl" "$FORVO_PRON/ForvoIcelandic.dsl"
ln -s "$FORVO_DSL/ForvoIndonesian.dsl" "$FORVO_PRON/ForvoIndonesian.dsl"
ln -s "$FORVO_DSL/ForvoIrish.dsl" "$FORVO_PRON/ForvoIrish.dsl"
ln -s "$FORVO_DSL/ForvoItalian.dsl" "$FORVO_PRON/ForvoItalian.dsl"
ln -s "$FORVO_DSL/ForvoJapanese.dsl" "$FORVO_PRON/ForvoJapanese.dsl"
ln -s "$FORVO_DSL/ForvoJin.dsl" "$FORVO_PRON/ForvoJin.dsl"
ln -s "$FORVO_DSL/ForvoKazakh.dsl" "$FORVO_PRON/ForvoKazakh.dsl"
ln -s "$FORVO_DSL/ForvoKorean.dsl" "$FORVO_PRON/ForvoKorean.dsl"
ln -s "$FORVO_DSL/ForvoLatin.dsl" "$FORVO_PRON/ForvoLatin.dsl"
ln -s "$FORVO_DSL/ForvoLatvian.dsl" "$FORVO_PRON/ForvoLatvian.dsl"
ln -s "$FORVO_DSL/ForvoLithuanian.dsl" "$FORVO_PRON/ForvoLithuanian.dsl"
ln -s "$FORVO_DSL/ForvoLuxembourgish.dsl" "$FORVO_PRON/ForvoLuxembourgish.dsl"
ln -s "$FORVO_DSL/ForvoMalay.dsl" "$FORVO_PRON/ForvoMalay.dsl"
ln -s "$FORVO_DSL/ForvoMandarin.dsl" "$FORVO_PRON/ForvoMandarin.dsl"
ln -s "$FORVO_DSL/ForvoMinDong.dsl" "$FORVO_PRON/ForvoMinDong.dsl"
ln -s "$FORVO_DSL/ForvoMinNan.dsl" "$FORVO_PRON/ForvoMinNan.dsl"
ln -s "$FORVO_DSL/ForvoMongolian.dsl" "$FORVO_PRON/ForvoMongolian.dsl"
ln -s "$FORVO_DSL/ForvoNahuatl.dsl" "$FORVO_PRON/ForvoNahuatl.dsl"
ln -s "$FORVO_DSL/ForvoNorwegian.dsl" "$FORVO_PRON/ForvoNorwegian.dsl"
ln -s "$FORVO_DSL/ForvoPersian.dsl" "$FORVO_PRON/ForvoPersian.dsl"
ln -s "$FORVO_DSL/ForvoPolish.dsl" "$FORVO_PRON/ForvoPolish.dsl"
ln -s "$FORVO_DSL/ForvoPortuguese.dsl" "$FORVO_PRON/ForvoPortuguese.dsl"
ln -s "$FORVO_DSL/ForvoPunjabi.dsl" "$FORVO_PRON/ForvoPunjabi.dsl"
ln -s "$FORVO_DSL/ForvoRomanian.dsl" "$FORVO_PRON/ForvoRomanian.dsl"
ln -s "$FORVO_DSL/ForvoRussian.dsl" "$FORVO_PRON/ForvoRussian.dsl"
ln -s "$FORVO_DSL/ForvoSanskrit.dsl" "$FORVO_PRON/ForvoSanskrit.dsl"
ln -s "$FORVO_DSL/ForvoScots.dsl" "$FORVO_PRON/ForvoScots.dsl"
ln -s "$FORVO_DSL/ForvoScottishGaelic.dsl" "$FORVO_PRON/ForvoScottishGaelic.dsl"
ln -s "$FORVO_DSL/ForvoSerbian.dsl" "$FORVO_PRON/ForvoSerbian.dsl"
ln -s "$FORVO_DSL/ForvoSlovak.dsl" "$FORVO_PRON/ForvoSlovak.dsl"
ln -s "$FORVO_DSL/ForvoSlovenian.dsl" "$FORVO_PRON/ForvoSlovenian.dsl"
ln -s "$FORVO_DSL/ForvoSouthwesternMandarin.dsl" "$FORVO_PRON/ForvoSouthwesternMandarin.dsl"
ln -s "$FORVO_DSL/ForvoSpanish.dsl" "$FORVO_PRON/ForvoSpanish.dsl"
ln -s "$FORVO_DSL/ForvoSwahili.dsl" "$FORVO_PRON/ForvoSwahili.dsl"
ln -s "$FORVO_DSL/ForvoSwedish.dsl" "$FORVO_PRON/ForvoSwedish.dsl"
ln -s "$FORVO_DSL/ForvoTagalog.dsl" "$FORVO_PRON/ForvoTagalog.dsl"
ln -s "$FORVO_DSL/ForvoTamil.dsl" "$FORVO_PRON/ForvoTamil.dsl"
ln -s "$FORVO_DSL/ForvoTatar.dsl" "$FORVO_PRON/ForvoTatar.dsl"
ln -s "$FORVO_DSL/ForvoThai.dsl" "$FORVO_PRON/ForvoThai.dsl"
ln -s "$FORVO_DSL/ForvoToisaneseCantonese.dsl" "$FORVO_PRON/ForvoToisaneseCantonese.dsl"
ln -s "$FORVO_DSL/ForvoTurkish.dsl" "$FORVO_PRON/ForvoTurkish.dsl"
ln -s "$FORVO_DSL/ForvoUkrainian.dsl" "$FORVO_PRON/ForvoUkrainian.dsl"
ln -s "$FORVO_DSL/ForvoUrdu.dsl" "$FORVO_PRON/ForvoUrdu.dsl"
ln -s "$FORVO_DSL/ForvoUyghur.dsl" "$FORVO_PRON/ForvoUyghur.dsl"
ln -s "$FORVO_DSL/ForvoUzbek.dsl" "$FORVO_PRON/ForvoUzbek.dsl"
ln -s "$FORVO_DSL/ForvoVietnamese.dsl" "$FORVO_PRON/ForvoVietnamese.dsl"
ln -s "$FORVO_DSL/ForvoWelsh.dsl" "$FORVO_PRON/ForvoWelsh.dsl"
ln -s "$FORVO_DSL/ForvoWu.dsl" "$FORVO_PRON/ForvoWu.dsl"
ln -s "$FORVO_DSL/ForvoXiang.dsl" "$FORVO_PRON/ForvoXiang.dsl"
ln -s "$FORVO_DSL/ForvoYiddish.dsl" "$FORVO_PRON/ForvoYiddish.dsl"
ln -s "$FORVO_DSL/ForvoZhuang.dsl" "$FORVO_PRON/ForvoZhuang.dsl"
ln -s "$FORVO_OPUS/af.zip" "$FORVO_PRON/ForvoAfrikaans.dsl.files.zip"
ln -s "$FORVO_OPUS/sq.zip" "$FORVO_PRON/ForvoAlbanian.dsl.files.zip"
ln -s "$FORVO_OPUS/grc.zip" "$FORVO_PRON/ForvoAncientGreek.dsl.files.zip"
ln -s "$FORVO_OPUS/ar.zip" "$FORVO_PRON/ForvoArabic.dsl.files.zip"
ln -s "$FORVO_OPUS/hy.zip" "$FORVO_PRON/ForvoArmenian.dsl.files.zip"
ln -s "$FORVO_OPUS/az.zip" "$FORVO_PRON/ForvoAzerbaijani.dsl.files.zip"
ln -s "$FORVO_OPUS/eu.zip" "$FORVO_PRON/ForvoBasque.dsl.files.zip"
ln -s "$FORVO_OPUS/be.zip" "$FORVO_PRON/ForvoBelarusian.dsl.files.zip"
ln -s "$FORVO_OPUS/bn.zip" "$FORVO_PRON/ForvoBengali.dsl.files.zip"
ln -s "$FORVO_OPUS/br.zip" "$FORVO_PRON/ForvoBreton.dsl.files.zip"
ln -s "$FORVO_OPUS/bg.zip" "$FORVO_PRON/ForvoBulgarian.dsl.files.zip"
ln -s "$FORVO_OPUS/yue.zip" "$FORVO_PRON/ForvoCantonese.dsl.files.zip"
ln -s "$FORVO_OPUS/ca.zip" "$FORVO_PRON/ForvoCatalan.dsl.files.zip"
ln -s "$FORVO_OPUS/hr.zip" "$FORVO_PRON/ForvoCroatian.dsl.files.zip"
ln -s "$FORVO_OPUS/cs.zip" "$FORVO_PRON/ForvoCzech.dsl.files.zip"
ln -s "$FORVO_OPUS/da.zip" "$FORVO_PRON/ForvoDanish.dsl.files.zip"
ln -s "$FORVO_OPUS/nl.zip" "$FORVO_PRON/ForvoDutch.dsl.files.zip"
ln -s "$FORVO_OPUS/en.zip" "$FORVO_PRON/ForvoEnglish.dsl.files.zip"
ln -s "$FORVO_OPUS/eo.zip" "$FORVO_PRON/ForvoEsperanto.dsl.files.zip"
ln -s "$FORVO_OPUS/et.zip" "$FORVO_PRON/ForvoEstonian.dsl.files.zip"
ln -s "$FORVO_OPUS/fi.zip" "$FORVO_PRON/ForvoFinnish.dsl.files.zip"
ln -s "$FORVO_OPUS/fr.zip" "$FORVO_PRON/ForvoFrench.dsl.files.zip"
ln -s "$FORVO_OPUS/fy.zip" "$FORVO_PRON/ForvoFrisian.dsl.files.zip"
ln -s "$FORVO_OPUS/gan.zip" "$FORVO_PRON/ForvoGan.dsl.files.zip"
ln -s "$FORVO_OPUS/ka.zip" "$FORVO_PRON/ForvoGeorgian.dsl.files.zip"
ln -s "$FORVO_OPUS/de.zip" "$FORVO_PRON/ForvoGerman.dsl.files.zip"
ln -s "$FORVO_OPUS/el.zip" "$FORVO_PRON/ForvoGreek.dsl.files.zip"
ln -s "$FORVO_OPUS/hak.zip" "$FORVO_PRON/ForvoHakka.dsl.files.zip"
ln -s "$FORVO_OPUS/he.zip" "$FORVO_PRON/ForvoHebrew.dsl.files.zip"
ln -s "$FORVO_OPUS/hi.zip" "$FORVO_PRON/ForvoHindi.dsl.files.zip"
ln -s "$FORVO_OPUS/hu.zip" "$FORVO_PRON/ForvoHungarian.dsl.files.zip"
ln -s "$FORVO_OPUS/is.zip" "$FORVO_PRON/ForvoIcelandic.dsl.files.zip"
ln -s "$FORVO_OPUS/ind.zip" "$FORVO_PRON/ForvoIndonesian.dsl.files.zip"
ln -s "$FORVO_OPUS/_ga.zip" "$FORVO_PRON/ForvoIrish.dsl.files.zip"
ln -s "$FORVO_OPUS/it.zip" "$FORVO_PRON/ForvoItalian.dsl.files.zip"
ln -s "$FORVO_OPUS/ja.zip" "$FORVO_PRON/ForvoJapanese.dsl.files.zip"
ln -s "$FORVO_OPUS/cjy.zip" "$FORVO_PRON/ForvoJin.dsl.files.zip"
ln -s "$FORVO_OPUS/kk.zip" "$FORVO_PRON/ForvoKazakh.dsl.files.zip"
ln -s "$FORVO_OPUS/ko.zip" "$FORVO_PRON/ForvoKorean.dsl.files.zip"
ln -s "$FORVO_OPUS/la.zip" "$FORVO_PRON/ForvoLatin.dsl.files.zip"
ln -s "$FORVO_OPUS/lv.zip" "$FORVO_PRON/ForvoLatvian.dsl.files.zip"
ln -s "$FORVO_OPUS/lt.zip" "$FORVO_PRON/ForvoLithuanian.dsl.files.zip"
ln -s "$FORVO_OPUS/lb.zip" "$FORVO_PRON/ForvoLuxembourgish.dsl.files.zip"
ln -s "$FORVO_OPUS/ms.zip" "$FORVO_PRON/ForvoMalay.dsl.files.zip"
ln -s "$FORVO_OPUS/zh.zip" "$FORVO_PRON/ForvoMandarinChinese.dsl.files.zip"
ln -s "$FORVO_OPUS/cdo.zip" "$FORVO_PRON/ForvoMinDong.dsl.files.zip"
ln -s "$FORVO_OPUS/nan.zip" "$FORVO_PRON/ForvoMinNan.dsl.files.zip"
ln -s "$FORVO_OPUS/mn.zip" "$FORVO_PRON/ForvoMongolian.dsl.files.zip"
ln -s "$FORVO_OPUS/nah.zip" "$FORVO_PRON/ForvoNahuatl.dsl.files.zip"
ln -s "$FORVO_OPUS/no.zip" "$FORVO_PRON/ForvoNorwegianBokmål.dsl.files.zip"
ln -s "$FORVO_OPUS/fa.zip" "$FORVO_PRON/ForvoPersian.dsl.files.zip"
ln -s "$FORVO_OPUS/pl.zip" "$FORVO_PRON/ForvoPolish.dsl.files.zip"
ln -s "$FORVO_OPUS/pt.zip" "$FORVO_PRON/ForvoPortuguese.dsl.files.zip"
ln -s "$FORVO_OPUS/pa.zip" "$FORVO_PRON/ForvoPunjabi.dsl.files.zip"
ln -s "$FORVO_OPUS/ro.zip" "$FORVO_PRON/ForvoRomanian.dsl.files.zip"
ln -s "$FORVO_OPUS/ru.zip" "$FORVO_PRON/ForvoRussian.dsl.files.zip"
ln -s "$FORVO_OPUS/sa.zip" "$FORVO_PRON/ForvoSanskrit.dsl.files.zip"
ln -s "$FORVO_OPUS/sco.zip" "$FORVO_PRON/ForvoScots.dsl.files.zip"
ln -s "$FORVO_OPUS/gd.zip" "$FORVO_PRON/ForvoScottishGaelic.dsl.files.zip"
ln -s "$FORVO_OPUS/sr.zip" "$FORVO_PRON/ForvoSerbian.dsl.files.zip"
ln -s "$FORVO_OPUS/sk.zip" "$FORVO_PRON/ForvoSlovak.dsl.files.zip"
ln -s "$FORVO_OPUS/sl.zip" "$FORVO_PRON/ForvoSlovenian.dsl.files.zip"
ln -s "$FORVO_OPUS/xghu.zip" "$FORVO_PRON/ForvoSouthwesternMandarin.dsl.files.zip"
ln -s "$FORVO_OPUS/es.zip" "$FORVO_PRON/ForvoSpanish.dsl.files.zip"
ln -s "$FORVO_OPUS/sw.zip" "$FORVO_PRON/ForvoSwahili.dsl.files.zip"
ln -s "$FORVO_OPUS/sv.zip" "$FORVO_PRON/ForvoSwedish.dsl.files.zip"
ln -s "$FORVO_OPUS/tl.zip" "$FORVO_PRON/ForvoTagalog.dsl.files.zip"
ln -s "$FORVO_OPUS/ta.zip" "$FORVO_PRON/ForvoTamil.dsl.files.zip"
ln -s "$FORVO_OPUS/tt.zip" "$FORVO_PRON/ForvoTatar.dsl.files.zip"
ln -s "$FORVO_OPUS/th.zip" "$FORVO_PRON/ForvoThai.dsl.files.zip"
ln -s "$FORVO_OPUS/tisa.zip" "$FORVO_PRON/ForvoToisaneseCantonese.dsl.files.zip"
ln -s "$FORVO_OPUS/tr.zip" "$FORVO_PRON/ForvoTurkish.dsl.files.zip"
ln -s "$FORVO_OPUS/uk.zip" "$FORVO_PRON/ForvoUkrainian.dsl.files.zip"
ln -s "$FORVO_OPUS/ur.zip" "$FORVO_PRON/ForvoUrdu.dsl.files.zip"
ln -s "$FORVO_OPUS/ug.zip" "$FORVO_PRON/ForvoUyghur.dsl.files.zip"
ln -s "$FORVO_OPUS/uz.zip" "$FORVO_PRON/ForvoUzbek.dsl.files.zip"
ln -s "$FORVO_OPUS/vi.zip" "$FORVO_PRON/ForvoVietnamese.dsl.files.zip"
ln -s "$FORVO_OPUS/cy.zip" "$FORVO_PRON/ForvoWelsh.dsl.files.zip"
ln -s "$FORVO_OPUS/wuu.zip" "$FORVO_PRON/ForvoWu.dsl.files.zip"
ln -s "$FORVO_OPUS/hsn.zip" "$FORVO_PRON/ForvoXiang.dsl.files.zip"
ln -s "$FORVO_OPUS/yi.zip" "$FORVO_PRON/ForvoYiddish.dsl.files.zip"
ln -s "$FORVO_OPUS/za.zip" "$FORVO_PRON/ForvoZhuang.dsl.files.zip"
echo ""

echo "Setup GoldenDictOCR"
echo "---"
rm "$GOLDENDICT_SRC/GoldenDictOCR/IncludeAHK/GdOcrTool.ahk"
rm "$GOLDENDICT_SRC/GoldenDictOCR/IncludeAHK/GoldenDict.ahk"
ln -s "$GOLDENDICT_DOTFILE/GoldenDictOCR/IncludeAHK/GdOcrTool.ahk" "$GOLDENDICT_SRC/GoldenDictOCR/IncludeAHK/GdOcrTool.ahk"
ln -s "$GOLDENDICT_DOTFILE/GoldenDictOCR/IncludeAHK/GoldenDict.ahk" "$GOLDENDICT_SRC/GoldenDictOCR/IncludeAHK/GoldenDict.ahk"

echo ""

# End of Script
read -p "Press [Enter] to continue..."

